version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - mvnw.cmd clean package -DskipTest

test_script:
  - mvnw.cmd clean verify

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.m2

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.7.0

matrix:
  fast_finish: true
